#!/bin/sh

# Set these paths appropriately

BIN=/home/trade/Téléchargements/treetagger/bin
CMD=/home/trade/Téléchargements/treetagger/cmd
LIB=/home/trade/Téléchargements/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
