#!/bin/sh

# Set these paths appropriately

BIN=/home/trade/Téléchargements/treetagger/bin
CMD=/home/trade/Téléchargements/treetagger/cmd
LIB=/home/trade/Téléchargements/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/polish-abbreviations-utf8
PARFILE=${LIB}/polish-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
